# Configuration Rubocop basique pour Foresy API
# Compatible avec rubocop de base (sans extensions externes)

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false

  # Exclure les fichiers auto-générés et non pertinents
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "public/**/*"
    - "storage/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - ".github/**/*"
    - "docker-compose*.yml"
    - "Dockerfile*"
    - "entrypoint.sh*"

# Style/FrozenStringLiteralComment - désactiver pour plus de flexibilité
Style/FrozenStringLiteralComment:
  Enabled: false

# Metrics/BlockLength - permettre des blocs plus longs pour les tests RSpec
Metrics/BlockLength:
  Enabled: true
  CountAsOne: "array"
  Exclude:
    - "spec/**/*"
    - "test/**/*"
  Max: 100

# Metrics/MethodLength - ajuster les limites selon le contexte
Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 50
  CountAsOne: []
  Exclude:
    - "spec/**/*"
    - "test/**/*"
    - "db/migrate/*"
    - "config/initializers/*"
    - "app/controllers/api/v1/missions_controller.rb"
    - "app/controllers/api/v1/cras_controller.rb"
    - "app/controllers/__test_support__/**/*"

# Metrics/AbcSize - augmenter la limite pour la complexité
Metrics/AbcSize:
  Enabled: true
  Max: 50
  Exclude:
    - "app/controllers/api/v1/missions_controller.rb"
    - "app/controllers/__test_support__/**/*"
    - "app/controllers/api/v1/cras_controller.rb"
    - "app/controllers/concerns/api/v1/cras/**/*"
    - "app/services/api/v1/cras/**/*"

# Metrics/CyclomaticComplexity - augmenter la limite
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 20
  Exclude:
    - "app/controllers/api/v1/cras_controller.rb"
    - "app/models/concerns/validatable.rb"

# Metrics/PerceivedComplexity - augmenter la limite
Metrics/PerceivedComplexity:
  Enabled: true
  Max: 25
  Exclude:
    - "app/models/concerns/validatable.rb"

# Layout/LineLength - permettre des lignes plus longues
Layout/LineLength:
  Enabled: true
  Max: 120

# Layout/IndentationWidth - configuration standard
Layout/IndentationWidth:
  Enabled: true
  Width: 2

# Style/Documentation - désactiver pour les contrôleurs et services
Style/Documentation:
  Enabled: false
  Exclude:
    - "app/controllers/**/*"
    - "app/services/**/*"
    - "app/models/**/*"

# Style/ClassAndModuleChildren - permettre les namespaces simples
Style/ClassAndModuleChildren:
  Enabled: false

# Style/EmptyMethod - permettre les méthodes vides avec des commentaires
Style/EmptyMethod:
  Enabled: false

# Metrics/ClassLength - augmenter la limite pour les classes de modèles
Metrics/ClassLength:
  Enabled: true
  Max: 300
  Exclude:
    - "spec/**/*"
    - "test/**/*"
    - "app/controllers/api/v1/missions_controller.rb"

# Metrics/ModuleLength - augmenter la limite pour les modules helper
Metrics/ModuleLength:
  Enabled: true
  Max: 200
  Exclude:
    - "spec/**/*"
    - "test/**/*"
    - "app/controllers/concerns/api/v1/**/*"
    - "app/controllers/concerns/common/**/*"

# Style/GuardClause - rendre plus flexible
Style/GuardClause:
  Enabled: false

# Style/IfUnlessModifier - permettre les modificateurs
Style/IfUnlessModifier:
  Enabled: true

# Style/Next - permettre les next dans les boucles
Style/Next:
  Enabled: true

# Style/WhileUntilModifier - permettre les modificateurs
Style/WhileUntilModifier:
  Enabled: true

# Style/SymbolProc - permettre les symboles comme blocs
Style/SymbolProc:
  Enabled: true

# Style/Lambda - permettre les lambda avec args
Style/Lambda:
  Enabled: true

# Style/TrailingCommaInHashLiteral - flexible pour les hashes
Style/TrailingCommaInHashLiteral:
  Enabled: false

# Style/HashSyntax - Ruby 1.9 style hash syntax
Style/HashSyntax:
  Enabled: true

# Style/RedundantReturn - permettre les returns redondants pour la lisibilité
Style/RedundantReturn:
  Enabled: false

# Naming/PredicateMethod - désactiver les faux positifs pour les méthodes setter/helper
Naming/PredicateMethod:
  Enabled: true
  AllowedMethods:
    - set_tags_with_modern_api
    - set_tags_with_legacy_api
    - add_attributes_datadog_modern_api
    - check_locked_and_render
    - check_creator_and_render
    - check_transition_and_render
    - execute_destroy_link

# Naming/AccessorMethodName - permettre get_ prefix pour clarté
Naming/AccessorMethodName:
  Enabled: false

# Naming/PredicateMethod - désactiver pour les concerns DDD
Naming/PredicateMethod:
  Enabled: false

# Style/SafeNavigationChainLength - désactiver pour les chaînes de navigation complexes
Style/SafeNavigationChainLength:
  Enabled: false

# Naming/PredicatePrefix - désactiver pour les noms personnalisés
Naming/PredicatePrefix:
  Enabled: false

# Naming/VariableNumber - permettre address_line_1, address_line_2, entry_mission_1
Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: normalcase
  AllowedIdentifiers:
    - address_line_1
    - address_line_2
    - entry_mission_1
    - entry_mission_2

# Lint/DuplicateBranch - désactiver pour les controllers avec gestion d'erreurs similaires
Lint/DuplicateBranch:
  Enabled: true
  Exclude:
    - "app/controllers/api/v1/missions_controller.rb"
    - "app/controllers/api/v1/cras_controller.rb"

# Lint/Void - désactiver pour les expressions de logging
Lint/Void:
  Enabled: true
  Exclude:
    - "app/controllers/concerns/**/*"
